name: Simple-Deployment-Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches: [main] 
    types: [opened, synchronize]

jobs:
  build:
    if: ${{ github.event_name == 'push' &&  contains(join(toJson(github.event.commits.*.message)), '#pipeline') }}
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install
        run: |
          npm install
      - name: build
        run: |
          ls -la
          npm run build
      - name: git status
        run: |
          git status          
      - name: working dir
        run: |
          cd public 
          pwd
          ls -la

      - name: lint
        run: npm run eslint

      - name: The job has failed
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        if: ${{ github.event_name == 'push' &&  ( ! contains(join(toJson(github.event.commits.*.message)), '#skip') ) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
